
auth.token=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

defaults.org=jung-tl
defaults.project=react-native

defaults.url=https://sentry.io/
